version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env  # לוודא שזה קיים ב־server

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
