version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://shakedcrissy18:Aeserhxh0210@cluster0.9kztbwf.mongodb.net/taskmanager?retryWrites=true&w=majority&appName=Cluster0

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
